cluster.name: docker-cluster
network.host: 0.0.0.0
#xpack.security.transport.ssl.enabled: true
#xpack.security.transport.ssl.verification_mode: certificate
#xpack.security.http.ssl.enabled: true
#xpack.security.http.ssl.client_authentication: optional
#xpack.security.http.ssl.key: certs/http.key
#xpack.security.http.ssl.certificate: certs/http.crt
#xpack.security.http.ssl.certificate_authorities: certs/ca.crt