app:
  name: "mszlu-ai"
server:
  mode: "debug" # gin的模式: debug, release, test
  host: "127.0.0.1" # 监听地址和端口
  port: 7777
  readTimeout: 10s # 读取超时时间（秒）
  writeTimeout: 30s # 写入超时时间（秒）
  cors:
    -  "*"