version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0 # 使用最新ES 8版本
    container_name: faber-elasticsearch
    environment:
      - xpack.security.enabled=true # 启用安全功能，ES 8 默认启用
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # root 用户密码
      - discovery.type=single-node # 单节点部署
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # 内存设置，根据实际情况调整
    volumes:
      - ${ROOT}\data\elasticsearch:/usr/share/elasticsearch/data
      - ${ROOT}\config\elasticsearch\elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ROOT}\plugins\elasticsearch:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200" # REST API 端口
      - "9300:9300" # 节点间通信端口
    restart: always
    networks:
      - my-app-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0 # 与ES版本匹配的Kibana
    container_name: faber-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://faber-elasticsearch:9200 # 连接到 Elasticsearch
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD} # Kibana系统用户密码
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    ports:
      - "5601:5601" # Kibana UI 端口
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - my-app-net

  redis:
    image: redis:7.2.4-alpine # 使用 Redis 最新稳定版，alpine 版本更轻量
    container_name: faber-redis
    command: redis-server --appendonly yes # 开启 AOF 持久化
    volumes:
      - ${ROOT}\data\redis:/data # 数据持久化
    ports:
      - "6379:6379" # Redis 默认端口
    restart: always
    networks:
      - my-app-net
  postgres:
    image: postgres:18 # 使用 18 版本 alpine 镜像，体积小
    container_name: faber-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres} # 数据库用户名
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}   # 数据库密码
      - POSTGRES_DB=${POSTGRES_DB}      # 默认创建的数据库名
      - TZ=Asia/Shanghai                          # 设置时区
      - Locale=zh_CN.UTF-8
    volumes:
      - ${ROOT}\data\postgres:/var/lib/postgresql # 数据持久化
    ports:
      - "15432:5432" # 映射端口
    networks:
      - my-app-net
    restart: always
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.25
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${ROOT}/data/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - my-app-net
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${ROOT}/data/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - my-app-net
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.6.7
    command: [ "milvus", "run", "standalone" ]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
    volumes:
      - ${ROOT}/data/milvus:/var/lib/milvus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    restart: always
    networks:
      - my-app-net
networks:
  my-app-net:
    driver: bridge